# Parsing TYNDP data for SHRECC

In [ ]:
import pandas as pd
import pickle
import os

%load_ext jupyter_black

# Import TYNDP data

In [ ]:
filepath_xlsb = "../data/tyndp/MMStandardOutputFile_DE2050_Plexos_CY2009_v11_SoS.xlsb"
filepath_prod_pkl = "../data/tyndp/DE2050_CY2009_prod.pkl"
filepath_trade_pkl = "../data/tyndp/DE2050_CY2009_trade.pkl"
filepath_concordance = "../data/tyndp/tyndp_ei_mapping.xlsx"

In [ ]:
if os.path.isfile(filepath_prod_pkl):
    with open(filepath_prod_pkl, "rb") as f:
        prod_DE2050_CY2009 = pickle.load(f)
else:
    prod_DE2050_CY2009 = pd.read_excel(
        io=filepath_xlsb,
        sheet_name="Hourly Market Data emarket",
        header=[10, 11, 12],
        index_col=[0, 1],
        engine="pyxlsb",
    )
    with open(filepath_prod_pkl, "wb") as f:
        pickle.dump(prod_DE2050_CY2009, f)

In [ ]:
# This is the raw data from TYNDP
# Parsing and cleaning includes:
# - keep only the columns with production data for nodes XX00, XX00RETE
# -
prod_DE2050_CY2009.dropna(axis=1, how="all")

Category        Gas CCGT old 2 [MW] Gas CCGT new [MW] Run-of-River [MW]  \
Country                        AL00              AL00              AL00
Date /Code                  AL00_13           AL00_14           AL00_26
1    01JAN00:00                   0               110               193
2    01JAN01:00                   0               100               193
3    01JAN02:00                   0                90               193
4    01JAN03:00                   0                 0               193
5    01JAN04:00                   0                 0               193
...                             ...               ...               ...
8732 30DEC19:00                   0                 0               407
8733 30DEC20:00                   0                 0               407
8734 30DEC21:00                   0                 0               407
8735 30DEC22:00                   0                 0               407
8736 30DEC23:00                   0                 0               407

Category        Reservoir [MW] Wind Onshore [MW] Solar (Photovoltaic) [MW]  \
Country                   AL00              AL00                      AL00
Date /Code             AL00_27           AL00_31                   AL00_33
1    01JAN00:00           1904                40                         0
2    01JAN01:00           1904                43                         0
3    01JAN02:00           1904                48                         0
4    01JAN03:00           1904                55                         0
5    01JAN04:00           1904                59                         0
...                        ...               ...                       ...
8732 30DEC19:00           1889               486                         0
8733 30DEC20:00           1889               485                         0
8734 30DEC21:00           1889               500                         0
8735 30DEC22:00           1889               535                         0
8736 30DEC23:00           1889               526                         0

Category        Demand [MW]\n(losses included) Balance [MW]  \
Country                                   AL00         AL00
Date /Code                           AL00_LOAD AL00_Balance
1    01JAN00:00                           1145         1102
2    01JAN01:00                           1006         1234
3    01JAN02:00                            923         1312
4    01JAN03:00                            885         1267
5    01JAN04:00                            892         1265
...                                        ...          ...
8732 30DEC19:00                           1752         1029
8733 30DEC20:00                           1654         1127
8734 30DEC21:00                           1483         1313
8735 30DEC22:00                           1290         1541
8736 30DEC23:00                           1080         1741

Category        Dumped Energy [MW] Energy Not Served [MW]  ...                \
Country                       AL00                   AL00  ...     UKNI SRES
Date /Code               AL00_Dump               AL00_ENS  ... UKNI SRES_ENS
1    01JAN00:00                  0                      0  ...             0
2    01JAN01:00                  0                      0  ...             0
3    01JAN02:00                  0                      0  ...             0
4    01JAN03:00                  0                      0  ...             0
5    01JAN04:00                  0                      0  ...             0
...                            ...                    ...  ...           ...
8732 30DEC19:00                  0                      0  ...             0
8733 30DEC20:00                  0                      0  ...             0
8734 30DEC21:00                  0                      0  ...             0
8735 30DEC22:00                  0                      0  ...             0
8736 30DEC23:00                  0                      0  ...             0

Category         Marginal Cost [€] Solar (Photovoltaic) [MW]  \
Country                  UKNI SRES                  UKNIRETE
Date /Code      UKNI SRES_Mgl Cost               UKNIRETE_33
1    01JAN00:00              -1000                         0
2    01JAN01:00              -1000                         0
3    01JAN02:00              -1000                         0
4    01JAN03:00              -1000                         0
5    01JAN04:00              -1000                         0
...                            ...                       ...
8732 30DEC19:00              -1000                         0
8733 30DEC20:00              -1000                         0
8734 30DEC21:00              -1000                         0
8735 30DEC22:00              -1000                         0
8736 30DEC23:00              -1000                         0

Category        CH4 Heat Pump (load) [MW] H2 Heat Pump (load) [MW]  \
Country                          UKNIRETE                 UKNIRETE
Date /Code                  UKNIRETE_HCH4             UKNIRETE_HH2
1    01JAN00:00                         0                        0
2    01JAN01:00                         0                        0
3    01JAN02:00                         0                        0
4    01JAN03:00                         0                        0
5    01JAN04:00                         0                        0
...                                   ...                      ...
8732 30DEC19:00                        19                       24
8733 30DEC20:00                        18                       24
8734 30DEC21:00                        17                       21
8735 30DEC22:00                        13                       17
8736 30DEC23:00                        10                       13

Category        Demand [MW]\n(losses included)     Balance [MW]  \
Country                               UKNIRETE         UKNIRETE
Date /Code                       UKNIRETE_LOAD UKNIRETE_Balance
1    01JAN00:00                           2214            -2214
2    01JAN01:00                           2206            -2206
3    01JAN02:00                           2177            -2177
4    01JAN03:00                           2173            -2173
5    01JAN04:00                           2150            -2150
...                                        ...              ...
8732 30DEC19:00                           1904            -1946
8733 30DEC20:00                           1883            -1925
8734 30DEC21:00                           1851            -1889
8735 30DEC22:00                           1824            -1854
8736 30DEC23:00                           1792            -1815

Category        Dumped Energy [MW] Energy Not Served [MW] Marginal Cost [€]
Country                   UKNIRETE               UKNIRETE          UKNIRETE
Date /Code           UKNIRETE_Dump           UKNIRETE_ENS UKNIRETE_Mgl Cost
1    01JAN00:00                  0                      0               237
2    01JAN01:00                  0                      0               233
3    01JAN02:00                  0                      0               231
4    01JAN03:00                  0                      0               231
5    01JAN04:00                  0                      0               231
...                            ...                    ...               ...
8732 30DEC19:00                  0                      0               160
8733 30DEC20:00                  0                      0               158
8734 30DEC21:00                  0                      0               158
8735 30DEC22:00                  0                      0               158
8736 30DEC23:00                  0                      0               158

[8736 rows x 2077 columns]

In [ ]:
sources = prod_DE2050_CY2009.columns.levels[0]

In [ ]:
concordance = pd.read_excel(
    filepath_concordance, sheet_name="concordance", index_col=0, skipfooter=1
).iloc[:, :-1]
concordance = concordance.loc[concordance.sum(1) > 0, concordance.sum() > 0]
concordance /= concordance.sum()
concordance.head()

,Gas CCGT CCS [MW],Gas CCGT new [MW],Gas CCGT old 1 [MW],Gas CCGT old 2 [MW],Gas CCGT present 1 [MW],Gas CCGT present 2 [MW],Gas OCGT new [MW],Gas OCGT old [MW],Gas conventional old 1 [MW],Gas conventional old 2 [MW],...,Others non-renewable [MW],Others renewable [MW],Pump Storage - Closed Loop (turbine) [MW],Pump Storage - Open Loop (turbine) [MW],Reservoir [MW],Run-of-River [MW],Solar (Photovoltaic) [MW],Solar (Thermal) [MW],Wind Offshore [MW],Wind Onshore [MW]
premise activity,,,,,,,,,,,,,,,,,,,,,
"electricity production, at biomass-fired IGCC power plant, pre, pipeline 200km, storage 1000m",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"electricity production, at co-generation natural gas-fired power plant, post, pipeline 200km, storage 1000m",0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"electricity production, at co-generation oil-fired power plant, post, pipeline 200km, storage 1000m",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"electricity production, at co-generation wood-fired power plant, post, pipeline 200km, storage 1000m",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"electricity production, at hard coal-fired IGCC power plant",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
country = "LU"
index_c = [c for c in prod_DE2050_CY2009.columns.levels[1] if c.startswith(country)]
index_c

['LUB1',
 'LUB1 SRES',
 'LUF1',
 'LUF1 SRES',
 'LUG1',
 'LUG1 EV Passenger Prosumer',
 'LUG1 EV Passenger Street',
 'LUG1 SRES',
 'LUG1RETE',
 'LUV1',
 'LUV1 SRES']

In [ ]:
idx = pd.IndexSlice

prod_DE2050_CY2009.loc[:, idx[:, index_c]].dropna(how="all", axis=1).sum().sort_values()

Category                        Country                     Date /Code
Marginal Cost [€]               LUV1 SRES                   LUV1 SRES_Mgl Cost                    -8736000
                                LUF1 SRES                   LUF1 SRES_Mgl Cost                    -8736000
                                LUB1 SRES                   LUB1 SRES_Mgl Cost                    -8736000
                                LUG1 SRES                   LUG1 SRES_Mgl Cost                    -8736000
Balance [MW]                    LUG1                        LUG1_Balance                          -3647483
                                                                                                    ...
Solar (Photovoltaic) [MW]       LUG1RETE                    LUG1RETE_33                            1711841
Demand [MW]\n(losses included)  LUG1 EV Passenger Prosumer  LUG1 EV Passenger Prosumer_LOAD        1958164
Marginal Cost [€]               LUG1 EV Passenger Prosumer  LUG1 EV Passenger Prosumer_Mgl Cost    2021255
Demand [MW]\n(losses included)  LUG1RETE                    LUG1RETE_LOAD                          4201208
                                LUG1                        LUG1_LOAD                              6155505
Length: 78, dtype: int64

In [ ]:
month = 4

sample = (
    prod_DE2050_CY2009.loc[:, idx[concordance.columns, index_c]]
    .dropna(how="all", axis=1)
    .iloc[month * 30 * 24 : (month * 30 + 7) * 24, :]
)

sample = sample.loc[:, sample.sum() > 0]

# ax = sample.plot.area(figsize=(10, 6))

In [ ]:
sample.plot()

:

In [ ]:
sample.sum() > 0

Category                                   Country   Date /Code
Hydrogen CCGT [MW]                         LUG1      LUG1_52         True
Others non-renewable [MW]                  LUG1      LUG1_36        False
Others renewable [MW]                      LUG1      LUG1_35        False
Pump Storage - Closed Loop (turbine) [MW]  LUV1      LUV1_29        False
Run-of-River [MW]                          LUG1      LUG1_26        False
Solar (Photovoltaic) [MW]                  LUG1      LUG1_33        False
                                           LUG1RETE  LUG1RETE_33    False
Wind Onshore [MW]                          LUG1      LUG1_31        False
dtype: bool

# Match with premise-ecoinvent inventories

The strategy is to recover the supply mixes for each country in a premise database.

In [50]:
import bw2data as bd

13:33:38+0100 [warning  ] Can't import `SimaProBlockCSVImporter` - please install `bw2io` with `pip install bw2io[multifunctional]` or install `multifunctional` and `bw_simapro_csv` manually.

In [51]:
bd.projects.set_current("IMMEC_Coupling")

In [54]:
image_SSP2_2100 = bd.Database("image_SSP2-RCP26_2100")

In [58]:
el_markets_WEU = [
    a
    for a in image_SSP2_2100
    if a["name"].startswith("market group for electricity,") and a["location"] == "WEU"
]

In [64]:
el_sources_WEU = set(
    e["name"]
    for a in el_markets_WEU
    for e in a.exchanges()
    if e["type"] == "technosphere"
)

In [69]:
pd.Series(list(el_sources_WEU)).to_clipboard()